application: ak-org
version: 1
runtime: php55
api_version: 1

handlers:
  
- url: /(.+\.php)$
  script: assets/\1
  
- url: /(.*\.(htm|html|css|js|img|png|jpg|map|woff|ttf))$
  static_files: assets/\1
  upload: assets/.*\.(htm|html|css|js|img|png|jpg|map|woff|ttf)$
  application_readable: true

  

